default_context:
  use_course: "yes"
  use_docs: "yes"
  use_cocalc: "yes"
  institution: "Washington State University (WSU)"
  department: "Physics"
  campus: "Pullman"
  campus_state: "WA"
  course_number: "521"
  course_section: "01"
  title: "Classical Mechanics"
  year: "2023"
  term: "Fall"
  class_time: "MWF, 11:10am - 12:00pm"
  class_room: "[Webster 941](https://sah-archipedia.org/buildings/WA-01-075-0008-13)"
  wsu_class_number: "03206"     # Listed next to course on https://schedules.wsu.edu/
  zoom_number: "941 0594 8181"
  canvas_url: "https://wsu.instructure.com/courses/1658144"
  perusall_url: "https://app.perusall.com/courses/2023-fall-physics-521-pullm-1-01-03206-classical-mechanics-i/"
  author: "Michael McNeil Forbes"
  author_email: "m.forbes+{{cookiecutter.course_number}}@wsu.edu"
  office: "Webster 947F"
  phone: "(509) 720-8095"
  office_hours: "TBD"
#  personnel:
#    instructors: ['Michael McNeil Forbes [`m.forbes+{{cookiecutter.course_number}}@wsu.edu`](mailto:m.forbes+{{cookiecutter.course_number}}@wsu.edu)']
#    assistants: ["TBA"]
  gitlab_url: "https://gitlab.com/wsu-courses/physics-521-classical-mechanics"
  github_url: "https://github.com/WSU-Physics-Courses/physics-521-classical-mechanics"

  # The following should get the resources and place them in _ext/Resources
  resources_url: "https://gitlab.com/wsu-courses/physics-521-classical-mechanics_resources"

  rtd: "physics-521-classical-mechanics-i"

  # This is the WSU Courses project... it usually does not change.
  cocalc_course_project: "c31d20a3-b0af-4bf7-a951-aa93a64395f6"

  # This is the Shared Project which changes for each class.
  cocalc_project: "c5a0bdae-e17c-46a1-ada4-78c6556d9429"

  nsf_grant: "2012190"

  # The remaining configuration options deal with provisioning of the environment etc.
  use_conda: "micromamba"
  use_pyproject: "no"
  use_manin: "yes"
  make_tools: "yes"
